server:
  port: 8080
spring:
  application:
    name: "auth"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"
adapters:
  r2dbc:
    host: localhost
    port: 3306
    database: ${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}